//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceClientAPIs.Pinterest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Pinterest.PinterestUser")]
    public interface PinterestUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PinterestUser/PinterestProfile", ReplyAction="http://tempuri.org/PinterestUser/PinterestProfileResponse")]
        string PinterestProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PinterestUser/PinterestProfile", ReplyAction="http://tempuri.org/PinterestUser/PinterestProfileResponse")]
        System.Threading.Tasks.Task<string> PinterestProfileAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PinterestUserChannel : WCFServiceClientAPIs.Pinterest.PinterestUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PinterestUserClient : System.ServiceModel.ClientBase<WCFServiceClientAPIs.Pinterest.PinterestUser>, WCFServiceClientAPIs.Pinterest.PinterestUser {
        
        public PinterestUserClient() {
        }
        
        public PinterestUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PinterestUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PinterestUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PinterestUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PinterestProfile() {
            return base.Channel.PinterestProfile();
        }
        
        public System.Threading.Tasks.Task<string> PinterestProfileAsync() {
            return base.Channel.PinterestProfileAsync();
        }
    }
}
